## YAML Template.
---
server:
  port: 8089
  
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  datasource:
    url: jdbc:h2:mem:accounts
    driverClassName: org.h2.Driver
    username: root
    password: qaz123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      
app:
  github:
    url: https://api.github.com/
    endpoints:
      users: /users
  